<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Auth2calls
 *
 * @author John Papagiannis <intelen>
 */
if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Auth2calls extends CI_Model {

	//put your code here


	function CreatePlanBasedOnQuestionaire($username = null) {

		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "https://socialenergy.it.fmi.uni-sofia.bg/webservice/rest/server.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		//curl_setopt($ch, CURLOPT_POSTFIELDS, "plan[username]=coolstone&plan[competencies][0][idnumber]=1.2&plan[competencies][1][idnumber]=1.3&wstoken=dd10d0e00b8c7d2a6c048e1475e61afd&wsfunction=local_socialenergy_competency_create_plan&moodlewsrestformat=json");
		//curl_setopt($ch, CURLOPT_POSTFIELDS, "plan[username]=$username&plan[competencies][0][idnumber]=1.2&plan[competencies][1][idnumber]=1.3&wstoken=dd10d0e00b8c7d2a6c048e1475e61afd&wsfunction=local_socialenergy_competency_create_plan&moodlewsrestformat=json");
		curl_setopt($ch, CURLOPT_POSTFIELDS, "plan[username]=$username&plan[competencies][0][idnumber]=2.1&plan[competencies][1][idnumber]=4.1&plan[competencies][2][idnumber]=6.1&wstoken=dd10d0e00b8c7d2a6c048e1475e61afd&wsfunction=local_socialenergy_competency_create_plan&moodlewsrestformat=json");

		curl_setopt($ch, CURLOPT_POST, 1);

		$headers = array();
		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			// echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		return json_decode($result, true);
	}

	function CreateClientUserToken($username, $password, $firstName, $lastName, $clientID, $clientScret) {

		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://socialauth.intelen.com/usercredClientUser.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=password&username=$username&password=$password&first_name=$firstName&last_name=$lastName");
		curl_setopt($ch, CURLOPT_POST, 1);
		//curl_setopt($ch, CURLOPT_USERPWD, "iccs2" . ":" . "secret2");
		curl_setopt($ch, CURLOPT_USERPWD, "$clientID" . ":" . "$clientScret");

		$headers = array();
		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			//  echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		return json_decode($result, true);
	}

	function CreateAccountToLcms($username, $firstname, $lastname, $email) {

		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "https://socialenergy.it.fmi.uni-sofia.bg/webservice/rest/server.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		//curl_setopt($ch, CURLOPT_POSTFIELDS, "userinfo[username]=coolstone&userinfo[firstname]=Atanas&userinfo[lastname]=Georgiev&userinfo[email]=coolstone@abv.bg&wstoken=dd10d0e00b8c7d2a6c048e1475e61afd&wsfunction=local_socialenergy_user_create_user&moodlewsrestformat=json");
		curl_setopt($ch, CURLOPT_POSTFIELDS, "userinfo[username]=$username&userinfo[firstname]=$firstname&userinfo[lastname]=$lastname&userinfo[email]=$email&wstoken=dd10d0e00b8c7d2a6c048e1475e61afd&wsfunction=local_socialenergy_user_create_user&moodlewsrestformat=json");
		curl_setopt($ch, CURLOPT_POST, 1);

		$headers = array();
		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			// echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		return json_decode($result, true);
	}

	function CreateUserToken($username, $password) {

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://socialauth.intelen.com/usercred.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=password&username=bshaffer&password=brent123");
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_USERPWD, "iccs2" . ":" . "secret2");

		$headers = array();
		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			// echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);


		return json_decode($result, true);
	}

	function ConfirmToken($token_id) {

		$ch = curl_init();
		$headers = [];
		$result;
		curl_setopt($ch, CURLOPT_URL, "https://servicessocialenergy.intelen.com/auth2/resource.php");
		//curl_setopt($ch, CURLOPT_URL, "http://localhost/auth2/resource.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "access_token=$token_id");
		curl_setopt($ch, CURLOPT_POST, 1);

		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			// echo 'Error:' . curl_error($ch);
		}

		curl_close($ch);
		return json_decode($result, true);
	}

	function getCodeToken($userID) {

		$ch = curl_init();
		// curl_setopt($ch, CURLOPT_URL, "http://localhost/auth2/authorize4.php?response_type=code&client_id=$userID&state=xyz");

		curl_setopt($ch, CURLOPT_URL, "https://servicessocialenergy.intelen.com/auth2/authorize4.php?response_type=code&client_id=$userID&state=xyz");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

		$headers = [];
		$headers[] = "Cache-Control: no-cache";
		$headers[] = "Postman-Token: f8b5b79c-348b-bc6f-7112-f145e1bfcaf6";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		return $result;
	}

	function getCodeRefreshToken($code, $userid, $userpass) {

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://servicessocialenergy.intelen.com/auth2/token.php"); //woriking
		//curl_setopt($ch, CURLOPT_URL, "https://servicessocialenergy.intelen.com/auth2/usercred.php");//old version
		//curl_setopt($ch, CURLOPT_URL, "http://localhost/auth2/usercred.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=authorization_code&code=$code");
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_USERPWD, "$userid" . ":" . "$userpass");

		$headers = [];
		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		return $result;
	}

	function RegisterAuth2($client_id, $client_secret) {

		$headers = [];
		$ch = curl_init();
		$result;
		curl_setopt($ch, CURLOPT_URL, "https://servicessocialenergy.intelen.com/auth2/token.php");
		//curl_setopt($ch, CURLOPT_URL, "http://localhost/auth2/token.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_USERPWD, "$client_id" . ":" . "$client_secret");

		$headers[] = "Content-Type: application/x-www-form-urlencoded";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			//  echo 'Error:' . curl_error($ch);
		}

		curl_close($ch);
		return json_decode($result, true);
	}

	function getProsumersfromRat($usrmail = "info@intelen.com", $token) {

		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, "https://rat.socialenergy-project.eu/consumers");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


		$headers = array();
		$headers[] = "Accept: application/json";
		$headers[] = "X-User-Email: $usrmail";
		$headers[] = "X-User-Token: $token";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			//  echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		return json_decode($result, true);
	}

	function connectToRat($usrmail, $token, $postVariable, $url = "https://rat.socialenergy-project.eu/scenarios") {

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://rat.socialenergy-project.eu/scenarios");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		$prosumersIDS = $postVariable["prosID"];
		
		curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"scenario\": {\"name\": \"abc2\", \"consumer_ids\": [$prosumersIDS], \"starttime\": \"" . $postVariable['searchDateFrom'] . "\", \"endtime\": \"" . $postVariable['searchDateTo'] . "\", \"interval_id\": " . $postVariable['IntervalPost'] . ", \"ecc_type_id\": " . $postVariable['eccTypePost'] . ",\"number_of_clusters\": ".$postVariable['number_of_clusters'].", \"energy_cost_parameter\": " . $postVariable['energyCosParPost'] . ", \"profit_margin_parameter\": " . $postVariable['profitMarginParameterPost'] . ", \"flexibility_id\": " . $postVariable['flexibility_factorPost'] . ", \"gamma_parameter\":" . $postVariable['gammaParameterPost'] . ", \"energy_program_ids\": [" . $postVariable['energyProgrmasIds'] . "]}}"); //[1,3,4]
		curl_setopt($ch, CURLOPT_POST, 1);

		$headers = [];
		$headers[] = "Accept: application/json";
		$headers[] = "Content-Type: application/json";
	
		$headers[] = "X-User-Email: $usrmail";
		$headers[] = "X-User-Token: $token";

		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

	

		return json_decode($result, true);
	}

	function exploitDataRowsTest($arrayTimeSeries) {

		$time_Series_data = [];
		$values_Series_data = [];
		$myEnergy_plot_data = [];

		$myEnergy_plot_data = $arrayTimeSeries;

		foreach ($myEnergy_plot_data as $key => $value) {

			if (is_array($myEnergy_plot_data[$key])) {

				$plot_data_energy_cost = [];
				$plot_data_energy_cost = $myEnergy_plot_data[$key];

				if (sizeof($plot_data_energy_cost) > 0) {

					foreach ($plot_data_energy_cost as $key2 => $value2) {

						if (is_numeric($value2)) {

							$values_Series_data[] = $value2;
						} else {

							$time_Series_data[] = $value2;
						}
					}
				}
			} else {
				
			}
		}

		return array($time_Series_data, $values_Series_data);
	}

	function exploitDataRows($arrayTimeSeries) {


		$time_Series_data = [];
		$values_Series_data = [];
		$myEnergy_plot_data = [];

		$myEnergy_plot_data = $arrayTimeSeries;
		$max3 = sizeof($myEnergy_plot_data);

		foreach ($myEnergy_plot_data as $key => $value) {

			if (is_array($myEnergy_plot_data[$key])) {

				$plot_data_energy_cost = [];
				$plot_data_energy_cost = $myEnergy_plot_data[$key];

				if (sizeof($plot_data_energy_cost) > 0) {

					foreach ($plot_data_energy_cost as $key2 => $value2) {

						if (is_array($plot_data_energy_cost[$key2])) {

							if (sizeof($plot_data_energy_cost[$key2]) > 0) {

								$plot_data_energy2 = [];
								$plot_data_energy2 = $plot_data_energy_cost[$key2];

								foreach ($plot_data_energy2 as $key3 => $value3) {

									if (is_array($plot_data_energy2[$key3])) {
										
									} else {

										if (is_numeric($value3)) {

											$values_Series_data[] = $value3;
										} else {

											$time_Series_data[] = $value3;
										}
									}
								}
							}
						} else {
							
						}
					}
				}
			} else {
				
			}
		}

		return array($time_Series_data, $values_Series_data);
	}

}
