<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Lcmsbridge
 *
 * @author John Papagiannis <intelen>
 * 
  if (!defined('BASEPATH'))
  exit('No direct script access allowed');

  class Generalpurposes extends CI_Model
 * 
 * 
 * 
 * 
 */
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lcmsbridge extends CI_Model
{

    //put your code here
    function getLoadLCMSActivity($userName = "")
    {

        $sql = "";
        $result;

        //$sql = "select UserName,EmailAddress from socialEnergy.UsersCredentials where UserName=" . $this->db->escape($userName) . "";
        $sql = "SELECT "
                . "IdRow,"
                . "CompTitle,"
                . "CompMainDesc,"
                . "RecordSavedAt,"
                . "userID"
                . " FROM LcmsStoreDataFromService where userID=" . $this->db->escape($userName) . " order by RecordSavedAt desc"; //where user_id=" . $this->db->escape($userName) . "";
      

        $result = $this->db->query($sql);
        return $result;
    }

    function filterGameValues($dbResult)
    {

        $data = [];
        $IdRow = [];
        $CompTitle = [];
        $CompMainDesc = [];
        $RecordSavedAt = [];
        $userID = [];


        $index = 0;

        foreach ($dbResult->result() as $row)
        {

            $IdRow[$index] = $row->IdRow;
            $CompTitle[$index] = $row->CompTitle;
            $CompMainDesc[$index] = $row->CompMainDesc;
            $RecordSavedAt[$index] = $row->RecordSavedAt;
            $userID[$index] = $row->userID;


            $index++;
        }

        $data["IdRow"] = $Row_id;
        $data["CompTitle"] = $CompTitle;
        $data["CompMainDesc"] = $CompMainDesc;
        $data["RecordSavedAt"] = $RecordSavedAt;
        $data["userID"] = $userID;



        return $data;
    }

    function getCodeRefreshToken($token = "dd10d0e00b8c7d2a6c048e1475e61afd")
    {

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $result = "";
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://socialenergy.it.fmi.uni-sofia.bg/webservice/rest/server.php");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "filters[0][column]=competencyframeworkid&filters[0][value]=3&wstoken=&wsfunction=core_competency_list_competencies&moodlewsrestformat=json");
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = [];
        $headers[] = "Content-Type: application/x-www-form-urlencoded";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch))
        {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);


        return $result;
    }

    function getUserProfileOnLcms($username = "student_katina")
    {

        $ch = curl_init();

        //$username ="intelen81";

        curl_setopt($ch, CURLOPT_URL, "https://socialenergy.it.fmi.uni-sofia.bg/webservice/rest/server.php");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "username=$username&wstoken=&wsfunction=local_socialenergy_user_get_profile&moodlewsrestformat=json");
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = array();
        $headers[] = "Content-Type: application/x-www-form-urlencoded";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch))
        {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

		
		
		
        return $result;
		
    }

}
